version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./logs:/var/log/autorent
    depends_on:
      - db
    networks:
      - autorent-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=autorent
      - MYSQL_USER=autorent_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - autorent-network

networks:
  autorent-network:
    driver: bridge

volumes:
  mysql-data: