version: '3.8'

services:
  backend:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./logs:/var/log/autorent
    networks:
      - autorent-network

networks:
  autorent-network:
    driver: bridge

volumes:
  mysql-data: